### ISSUE TITLE
Login Page (from Home) Google OAuth Login - User Story 4

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_web#6]
## Feature: Login Page
As a visitor, when I visit the login page “/login”,

- [x] I see a link to Log in with Google:

- [ ] When I click the link, I am taken to login through my google account, and I am redirected to the users's show page
(currently we are redirecting to the "/login" page until we can resolve the home page error)

## Navigation:
Link: "Login with Google"

## Sad Path:

- to be determined

**Comment by MelTravelz** [comment]
**Updates Needed:** 

- The redirect changed to the user's show page

**Comment by MelTravelz** [comment]
**Question**

- Since nothing really happens on this login page except needing to click another link, I've added that that link to Google on the `Login/Register` "button" on the homepage. All tests pass and it works in the browser, so we might consider deleting this page?  (Also, I left the original link commented out in the view, in case we decide to keep the login page.)
